Repository jaoafa/MyMaid4, pull requests merged in 2021-08, with the labels that each got.

#551 fix: #533 埋めてあるマップは除外
  src/main/java/com/jaoafa/mymaid4/event/Event_AntiToolbar.java
Labels: 🐛bug

#552 fix: #457 wt時、ワールド名が正常に表示されない不具合を修正
  src/main/java/com/jaoafa/mymaid4/command/Cmd_Wt.java
Labels: 🐛bug

#557 feat: Rollbarによるエラーレポーティングを追加
  pom.xml
  src/main/java/com/jaoafa/mymaid4/Main.java
  src/main/java/com/jaoafa/mymaid4/command/Cmd_Bug.java
  src/main/java/com/jaoafa/mymaid4/command/Cmd_Help.java
  src/main/java/com/jaoafa/mymaid4/command/Cmd_InvSave.java
  src/main/java/com/jaoafa/mymaid4/discordEvent/DiscordEvent_ListCmd.java
  src/main/java/com/jaoafa/mymaid4/event/Event_AntiToolbar.java
  src/main/java/com/jaoafa/mymaid4/event/Event_JoinWarnUsers.java
  src/main/java/com/jaoafa/mymaid4/event/Event_LoginSuccessful.java
  src/main/java/com/jaoafa/mymaid4/event/Event_LongTimeNoSee.java
  src/main/java/com/jaoafa/mymaid4/event/Event_MCBansLoginCheck.java
  src/main/java/com/jaoafa/mymaid4/event/Event_PlayerCheckPreLogin.java
  src/main/java/com/jaoafa/mymaid4/event/Event_ServerException.java
  src/main/java/com/jaoafa/mymaid4/event/Event_ViaVerCheck.java
  src/main/java/com/jaoafa/mymaid4/event/Event_Vote.java
  src/main/java/com/jaoafa/mymaid4/lib/Blacklist.java
  src/main/java/com/jaoafa/mymaid4/lib/DedMessage.java
  src/main/java/com/jaoafa/mymaid4/lib/Historyjao.java
  src/main/java/com/jaoafa/mymaid4/lib/MyMaidConfig.java
  src/main/java/com/jaoafa/mymaid4/lib/MyMaidLibrary.java
  src/main/java/com/jaoafa/mymaid4/lib/PlayerVoteDataMCJP.java
  src/main/java/com/jaoafa/mymaid4/lib/PlayerVoteDataMono.java
  src/main/java/com/jaoafa/mymaid4/lib/SelClickManager.java
  src/main/java/com/jaoafa/mymaid4/lib/TpDeny.java
Labels: ✨enhancement

#558 fix: rollbarにコードバージョンと環境を渡すように
  src/main/java/com/jaoafa/mymaid4/Main.java
Labels: ♻improvement

#564 dedmessageのlistの改ページdtのままでしたよ
  src/main/java/com/jaoafa/mymaid4/command/Cmd_DedMessage.java
Labels: 🐛bug
