Repository jaoafa/MyMaid4, pull requests merged in 2021-05, with the labels that each got.

#304 feat: #303 signコマンドの追加
  pom.xml
  src/main/java/com/jaoafa/mymaid4/Main.java
  src/main/java/com/jaoafa/mymaid4/command/Cmd_Sign.java
  src/main/java/com/jaoafa/mymaid4/event/Event_Sign.java
  src/main/java/com/jaoafa/mymaid4/lib/MyMaidData.java
  src/main/java/com/jaoafa/mymaid4/lib/MyMaidLibrary.java
Labels: ✨enhancement, 🚧Status: In Progress

#305 feat: #185 ブラックリストの代替製作完了
  src/main/java/com/jaoafa/mymaid4/Main.java
  src/main/java/com/jaoafa/mymaid4/command/Cmd_MyMaid4.java
  src/main/java/com/jaoafa/mymaid4/event/Event_BlackList.java
  src/main/java/com/jaoafa/mymaid4/lib/Blacklist.java
  src/main/java/com/jaoafa/mymaid4/lib/MyMaidData.java
Labels: ✨enhancement, 🚧Status: In Progress

#306 fix: #146 killコマンドの仕様変更
  src/main/java/com/jaoafa/mymaid4/event/Event_AntiProblemCommand.java
  src/main/java/com/jaoafa/mymaid4/lib/SelectorParser.java
Labels: ♻improvement, 🐛bug, 🚧Status: In Progress

#307 fix: 棒以外でもsignがいじれてしまっていた問題を修正
  src/main/java/com/jaoafa/mymaid4/event/Event_Sign.java
Labels: 🐛bug, 🚧Status: In Progress

#314 feat: #312 プルリクテンプレートの追加
  .github/pull_request_template.md
Labels: documentation, 🚧Status: In Progress

#316 fix: エリトラなどの着けるものを手動でつけられない・外せない不具合の修正
  src/main/java/com/jaoafa/mymaid4/event/Event_BlackList.java
Labels: 🐛bug, 🚧Status: In Progress

#317 fix: pull request template
  .github/pull_request_template.md
Labels: documentation, 🚧Status: In Progress

#319 feat: bugコマンドの追加
  src/main/java/com/jaoafa/mymaid4/Main.java
  src/main/java/com/jaoafa/mymaid4/command/Cmd_Bug.java
  src/main/java/com/jaoafa/mymaid4/event/Event_Bug.java
  src/main/java/com/jaoafa/mymaid4/lib/MyMaidConfig.java
Labels: ✨enhancement, 🚧Status: In Progress

#320 fix: bug, kickコマンドを引数無しで実行した際にエラーが発生する不具合の修正
  src/main/java/com/jaoafa/mymaid4/event/Event_AntiProblemCommand.java
Labels: 🐛bug, 🚧Status: In Progress

#321 fix: IllegalArgumentException: pitch not finite
  src/main/java/com/jaoafa/mymaid4/event/Event_Looking.java
Labels: 🐛bug, 🚧Status: In Progress

#329 fix: #328 jaoium判定条件の修正
  src/main/java/com/jaoafa/mymaid4/event/Event_Antijaoium.java
Labels: 🐛bug, 🚧Status: In Progress

#330 fix: #309 isInfiniteだった
  src/main/java/com/jaoafa/mymaid4/event/Event_Looking.java
Labels: 🐛bug, 🚧Status: In Progress

#331 fix: bintrayのリポジトリ削除
  pom.xml
Labels: 🐛bug, 🚧Status: In Progress

#332 feat: ツールバーの利用制限機能追加
  src/main/java/com/jaoafa/mymaid4/Main.java
  src/main/java/com/jaoafa/mymaid4/event/Event_AntiTeleportToNewPlayers.java
  src/main/java/com/jaoafa/mymaid4/event/Event_AntiTeleportToSpectator.java
  src/main/java/com/jaoafa/mymaid4/event/Event_AntiToolbar.java
  src/main/java/com/jaoafa/mymaid4/lib/MyMaidData.java
Labels: ✨enhancement, 🚧Status: In Progress

#333 feat: コマンド・イベント登録時のエラーメッセージを明確化
  src/main/java/com/jaoafa/mymaid4/Main.java
Labels: ♻improvement, 🚧Status: In Progress

#336 fix: #334 一部ブロックがdedmessageの対象にならない不具合の修正
  src/main/java/com/jaoafa/mymaid4/event/Event_DedMessage.java
  src/main/java/com/jaoafa/mymaid4/lib/DedMessage.java
Labels: 🐛bug, 🚧Status: In Progress

#339 feat: #324 helpコマンドの実装
  src/main/java/com/jaoafa/mymaid4/command/Cmd_Help.java
Labels: ✨enhancement, 🚧Status: In Progress

#343 fix: 悪意のあるアイテムを追加
  src/main/java/com/jaoafa/mymaid4/event/Event_Antijaoium.java
Labels: ♻improvement, 🚧Status: In Progress

#344 chore: CONTRIBUTINGの変更
  CONTRIBUTING.md
Labels: documentation, 🚧Status: In Progress

#347 Feature/issue 346 jaoium
  src/main/java/com/jaoafa/mymaid4/event/Event_Antijaoium.java
Labels: ♻improvement, 🚧Status: In Progress

#349 feat: 難易度管理・プロジェクトへの自動追加を実施するように
  .github/card-labeler.yml
  .github/workflows/set-projects.yml
Labels: ♻improvement

#355 fix: #354 okhttpのバージョンダウン
  pom.xml
  src/main/java/com/jaoafa/mymaid4/command/Cmd_Bug.java
Labels: 🐛bug

#377 fix: コマンド登録時、NoClassDefFoundErrorがエラーとして出る問題を修正
  src/main/java/com/jaoafa/mymaid4/Main.java
Labels: 🐛bug

#378 fix: WorldEditが全イベントで必須化されてしまっている不具合を修正
  src/main/java/com/jaoafa/mymaid4/Main.java
  src/main/java/com/jaoafa/mymaid4/command/Cmd_Calctree.java
  src/main/java/com/jaoafa/mymaid4/command/Cmd_DedMessage.java
  src/main/java/com/jaoafa/mymaid4/lib/MyMaidLibrary.java
Labels: 🐛bug

#405 fix: インベントリに同じアイテムがある場合にtoolbarとして判定しないように
  src/main/java/com/jaoafa/mymaid4/event/Event_AntiToolbar.java
Labels: 🐛bug

#407 fix: toolbar関連のnullpointerexception
  src/main/java/com/jaoafa/mymaid4/event/Event_AntiToolbar.java
Labels: 🐛bug

#409 wireコマンド
  src/main/java/com/jaoafa/mymaid4/command/Cmd_wire.java
  src/main/java/com/jaoafa/mymaid4/event/Event_AntiKillWireUnit.java
Labels: ✨enhancement

#415 feat: #261 入退出時にプレイヤー数を表示するように
  src/main/java/com/jaoafa/mymaid4/event/Event_PlayerCountNotify.java
  src/main/java/com/jaoafa/mymaid4/lib/MyMaidLibrary.java
Labels: ✨enhancement

#417 chore: toolbarアイテムのうちjaoiumだけ許可するように
  src/main/java/com/jaoafa/mymaid4/event/Event_AntiToolbar.java
  src/main/java/com/jaoafa/mymaid4/event/Event_Antijaoium.java
  src/main/java/com/jaoafa/mymaid4/lib/MyMaidLibrary.java
Labels: ♻improvement

#419 fix: #394 tempmute時、pigeonで発せられたメッセージの無効化
  src/main/java/com/jaoafa/mymaid4/lib/CarrierPigeon.java
Labels: ♻improvement

#420 fix: #379 blacklistの過度通知改善
  src/main/java/com/jaoafa/mymaid4/lib/Blacklist.java
Labels: 🐛bug

#421 feat: #375 氷を解けなくした
  src/main/java/com/jaoafa/mymaid4/event/Event_NotFadeIce.java
Labels: ✨enhancement

#422 feat: #371 tpコマンドによるテレポート時にDiscord#server-chatでもそれを表示するように
  src/main/java/com/jaoafa/mymaid4/event/Event_NotifyTPDiscord.java
Labels: ✨enhancement

#423 fix: #268 コマンドブロックからwtコマンドが実行された際にうまく動作しない不具合
  src/main/java/com/jaoafa/mymaid4/command/Cmd_Wt.java
Labels: 🐛bug

#424 fix: #263 coコマンドなどにおいて、引数なしだとエラーになる不具合
  src/main/java/com/jaoafa/mymaid4/event/Event_ManageCPPerms.java
Labels: 🐛bug

#425 feat: #364 TNTカートを設置できないように
  src/main/java/com/jaoafa/mymaid4/event/Event_AntiTNTCart.java
Labels: ✨enhancement

#426 feat: #414 エンドポータルの設置禁止
  src/main/java/com/jaoafa/mymaid4/event/Event_AntiEndPortal.java
  src/main/java/com/jaoafa/mymaid4/event/Event_AntiWither.java
  src/main/java/com/jaoafa/mymaid4/lib/MyMaidLibrary.java
Labels: ✨enhancement

#427 feat: sel polyを用いた3地点以上の同時選択への対応、glowing効果時間の修正
  src/main/java/com/jaoafa/mymaid4/command/Cmd_wire.java
Labels: ♻improvement

#428 fix: #413 bugの本かどうかをNBTタグで判定するように
  src/main/java/com/jaoafa/mymaid4/command/Cmd_Bug.java
  src/main/java/com/jaoafa/mymaid4/event/Event_Bug.java
  src/main/java/com/jaoafa/mymaid4/lib/NMSManager.java
Labels: 🐛bug

#430 fix: #429 Headで出した頭をホットバーに置くとAntiToolBarに引っかかる
  src/main/java/com/jaoafa/mymaid4/event/Event_AntiToolbar.java
Labels: 🐛bug
