Repository jaoafa/MyMaid4, pull requests merged in 2021-03, with the labels that each got.

#35 feat: テストを追加
  src/main/java/com/jaoafa/mymaid4/lib/ClassFinder.java
  src/test/java/com/jaoafa/mymaid4/MainTest.java
Labels: enhancement

#36 feat: SSKColorsを実装
  src/main/java/com/jaoafa/mymaid4/event/Event_SSKColor.java
  src/main/java/com/jaoafa/mymaid4/lib/SKKColorManager.java
Labels: enhancement

#41 chore: CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: documentation

#43 chore: Change CONTRIBUTING
  CONTRIBUTING.md
Labels: documentation

#44 feat: dtコマンド
  .idea/misc.xml
  README.md
  pom.xml
  src/main/java/com/jaoafa/mymaid4/Main.java
  src/main/java/com/jaoafa/mymaid4/command/Cmd_DT.java
  src/main/java/com/jaoafa/mymaid4/lib/MyMaidConfig.java
  src/main/java/com/jaoafa/mymaid4/lib/MyMaidLibrary.java
Labels: enhancement

#47 refactor close: SSKColors #37
  src/main/java/com/jaoafa/mymaid4/event/Event_SSKColor.java
  src/main/java/com/jaoafa/mymaid4/lib/SKKColorManager.java
Labels: refactor

#48 chore: CONTRIBUTINGにTODOの追加記述を追加
  CONTRIBUTING.md
Labels: documentation

#49 fix: CONTRIBUTINGの無駄な改行
  CONTRIBUTING.md
Labels: documentation

#50 feat: elytraを実装
  src/main/java/com/jaoafa/mymaid4/command/Cmd_Elytra.java
Labels: enhancement

#51 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: enhancement

#54 fix: ビルドテストエラーメッセージ修正
  src/test/java/com/jaoafa/mymaid4/MainTest.java
Labels: bug

#59 feat jail
  .idea/codeStyles/Project.xml
  src/main/java/com/jaoafa/mymaid4/command/Cmd_Jail.java
  src/main/java/com/jaoafa/mymaid4/event/Event_Jail.java
  src/main/java/com/jaoafa/mymaid4/lib/Jail.java
  src/main/java/com/jaoafa/mymaid4/lib/MyMaidConfig.java
  src/main/java/com/jaoafa/mymaid4/lib/MyMaidLibrary.java
Labels: enhancement

#61 fix: データベーステーブル名変更に伴う修正
  src/main/java/com/jaoafa/mymaid4/lib/Jail.java
Labels: bug

#62 feat: discordlink コマンドの追加
  src/main/java/com/jaoafa/mymaid4/command/Cmd_DiscordLink.java
  src/main/java/com/jaoafa/mymaid4/lib/Jail.java
Labels: enhancement

#63 fix: ファイル・クラス名が不適切な問題を修正
  src/main/java/com/jaoafa/mymaid4/event/Event_SKKColor.java
Labels: bug

#65 fix: mikeprimm-repoのhttps化
  pom.xml
Labels: bug

#42 feat: AntiProblemCommand
  src/main/java/com/jaoafa/mymaid4/event/Event_AntiProblemCommand.java
  src/main/java/com/jaoafa/mymaid4/lib/MyMaidConfig.java
  src/main/java/com/jaoafa/mymaid4/lib/MyMaidData.java
  src/main/java/com/jaoafa/mymaid4/lib/MyMaidLibrary.java
  src/main/java/com/jaoafa/mymaid4/lib/SelectorParser.java
Labels: enhancement

#66 fix: Jailの紐づけ解除バグ修正
  src/main/java/com/jaoafa/mymaid4/lib/Jail.java
Labels: bug

#69 feat: jaoHistory
  src/main/java/com/jaoafa/mymaid4/command/Cmd_History.java
  src/main/java/com/jaoafa/mymaid4/event/Event_History.java
  src/main/java/com/jaoafa/mymaid4/lib/Historyjao.java
Labels: enhancement

#68 feat: eban
  src/main/java/com/jaoafa/mymaid4/command/Cmd_EBan.java
  src/main/java/com/jaoafa/mymaid4/event/Event_EBan.java
  src/main/java/com/jaoafa/mymaid4/lib/EBan.java
Labels: enhancement

#71 chore: actionsのCIでキャッシュを使用するように
  .github/workflows/build.yml
  .idea/misc.xml
Labels: enhancement

#77 delete: Selclick
  src/main/java/com/jaoafa/mymaid4/command/Cmd_Selclick.java
  src/main/java/com/jaoafa/mymaid4/event/Event_ClearSelection.java
  src/main/java/com/jaoafa/mymaid4/lib/SelClickManager.java
Labels: refactor

#80 feat: GetUserKeyの追加
  src/main/java/com/jaoafa/mymaid4/command/Cmd_GetUserKey.java
Labels: enhancement

#82 feat: tempmute
  src/main/java/com/jaoafa/mymaid4/command/Cmd_TempMute.java
  src/main/java/com/jaoafa/mymaid4/event/Event_TempMute.java
  src/main/java/com/jaoafa/mymaid4/lib/MyMaidData.java
  src/main/java/com/jaoafa/mymaid4/lib/MyMaidLibrary.java
Labels: enhancement

#84 chore: 負荷軽減策(既に解除されていてもデータを保持するようにする)
  src/main/java/com/jaoafa/mymaid4/lib/ChatBan.java
  src/main/java/com/jaoafa/mymaid4/lib/EBan.java
  src/main/java/com/jaoafa/mymaid4/lib/Jail.java
Labels: refactor

#85 chore: CodeQLでキャッシュを使うように
  .github/workflows/codeql-analysis.yml
Labels: enhancement

#86 feat: #83の一部追加
  pom.xml
  src/main/java/com/jaoafa/mymaid4/command/Cmd_SetHome.java
  src/main/java/com/jaoafa/mymaid4/event/Event_Jail.java
  src/main/java/com/jaoafa/mymaid4/lib/Jail.java
Labels: enhancement

#87 fix: jSA2のソース取得に失敗する問題
  .mvn/maven.config
  pom.xml
  settings.xml
Labels: bug

#88 chore: READMEとCONTRIBUTINGの変更
  CONTRIBUTING.md
  README.md
Labels: enhancement

#89 chore: ボード(プロジェクト)の場所変更に伴い修正
  CONTRIBUTING.md
  README.md
Labels: enhancement

#90 feat: dependabot
  .github/dependabot.yml
Labels: enhancement

#95 feat: CmdLengthLimiter
  src/main/java/com/jaoafa/mymaid4/event/Event_CmdLengthLimiter.java
Labels: enhancement

#96 feat: AntiLoginCmd
  src/main/java/com/jaoafa/mymaid4/event/Event_AntiLoginCmd.java
Labels: enhancement

#98 feat: AntiTargetAllEntityを実装
  .idea/misc.xml
  src/main/java/com/jaoafa/mymaid4/event/Event_AntiLoginCmd.java
  src/main/java/com/jaoafa/mymaid4/event/Event_AntiTargetAllEntityCmd.java
  src/main/java/com/jaoafa/mymaid4/event/Event_ChatBan.java
  src/main/java/com/jaoafa/mymaid4/event/Event_EBan.java
  src/main/java/com/jaoafa/mymaid4/event/Event_SKKColor.java
  src/main/java/com/jaoafa/mymaid4/event/Event_TempMute.java
Labels: enhancement

#97 change: CmdLengthLimiterを緑に
  src/main/java/com/jaoafa/mymaid4/event/Event_CmdLengthLimiter.java
Labels: enhancement

#102 chore: jSA2 ea05986リリースに伴いアップデート
  pom.xml
Labels: dependencies

#103 feat: jaoium規制
  .idea/codeStyles/Project.xml
  src/main/java/com/jaoafa/mymaid4/event/Event_Antijaoium.java
  src/main/java/com/jaoafa/mymaid4/lib/ChatBan.java
  src/main/java/com/jaoafa/mymaid4/lib/EBan.java
  src/main/java/com/jaoafa/mymaid4/lib/Jail.java
  src/main/java/com/jaoafa/mymaid4/tasks/Task_AutoRemoveJailByjaoium.java
Labels: enhancement

#105 fix: #78
  src/main/java/com/jaoafa/mymaid4/event/Event_AntiProblemCommand.java
Labels: bug

#99 wtコマンドの実装 + 爆発によって絵画などが壊れないように
  src/main/java/com/jaoafa/mymaid4/command/Cmd_Wt.java
  src/main/java/com/jaoafa/mymaid4/event/Event_Explosion.java
  src/main/java/com/jaoafa/mymaid4/lib/MyMaidLibrary.java
Labels: enhancement

#106 feat: LoginSuccessful
  src/main/java/com/jaoafa/mymaid4/event/Event_LoginSuccessful.java
  src/main/java/com/jaoafa/mymaid4/event/Event_PlayerCheckPreLogin.java
Labels: enhancement

#108 refactor: chatコマンド
  src/main/java/com/jaoafa/mymaid4/command/Cmd_Chat.java
  src/main/java/com/jaoafa/mymaid4/lib/MyMaidLibrary.java
Labels: refactor
