Repository jaoafa/MyMaid4, pull requests merged in 2022-08, with the labels that each got.

#901 /walkspeed,flyspeed reset を実装 & デフォルト値を修正
  src/main/java/com/jaoafa/mymaid4/command/Cmd_FlySpeed.java
  src/main/java/com/jaoafa/mymaid4/command/Cmd_WalkSpeed.java
Labels: 🐛bug, ♻improvement

#903 feat: #895 MCBansキャッシュを使う
  src/main/java/com/jaoafa/mymaid4/event/Event_FirstLogin.java
  src/main/java/com/jaoafa/mymaid4/lib/MCBans.java
  src/main/java/com/jaoafa/mymaid4/lib/MCBansCache.java
Labels: ♻improvement

#904 fix: なぜかログイン時のMCBansチェックがコミットされてなかった
  src/main/java/com/jaoafa/mymaid4/event/Event_MCBansLoginCheck.java
Labels: 🐛bug

#908 feat: #906 opコマンドの制限追加
  src/main/java/com/jaoafa/mymaid4/event/Event_AntiProblemCommand.java
Labels: ♻improvement

#909 feat: #900 自動でレビュアーを追加する
  .github/workflows/add-reviewer.yml
Labels: ♻improvement

#910 fix: MCBansCacheのパラメーターがidではなくplayerIdだった
  src/main/java/com/jaoafa/mymaid4/lib/MCBansCache.java
Labels: 🐛bug

#913 fix: プレイヤーの頭がツールバー判定される問題の修正
  src/main/java/com/jaoafa/mymaid4/event/Event_AntiToolbar.java
Labels: 🐛bug

#915 chore: Issueラベルの名前変更
  .github/card-labeler.yml
  CONTRIBUTING.md
Labels: ♻improvement

#918 fix: #917 lastCheckedAtはStringなのにgetLongでとってた不具合の修正
  src/main/java/com/jaoafa/mymaid4/lib/MCBansCache.java
Labels: 🐛bug

#919 fix(DailyOnlineTime): #916 Mapに対象のUUIDキーがない場合にエラーが出る不具合修正
  src/main/java/com/jaoafa/mymaid4/event/Event_DailyOnlineTime.java
Labels: 🐛bug

#920 feat(Chat): プレイヤー名部分をクォートして指定できるように
  src/main/java/com/jaoafa/mymaid4/command/Cmd_Chat.java
Labels: ♻improvement

#921 fix: 実行したコマンドを全権限で表示するように
  src/main/java/com/jaoafa/mymaid4/event/Event_CommandFeedback.java
  src/main/java/com/jaoafa/mymaid4/event/Event_CommandSender.java
Labels: ♻improvement

#927 fix(blacklist): なんかTELLの言い回しが変だから修正
  src/main/java/com/jaoafa/mymaid4/lib/Blacklist.java
Labels: ♻improvement

#937 feat: サバイバルモード/アドベンチャーモードでsit/layを使えないように
  src/main/java/com/jaoafa/mymaid4/event/Event_SurvivalSitLay.java
Labels: ✨enhancement
