Repository jaoafa/MyMaid4, pull requests merged in 2022-03, with the labels that each got.

#719 依存パッケージアップデート 2022/03/08
  .github/workflows/PaperServerTest.yml
  .github/workflows/build.yml
  .github/workflows/check-system-print.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/dependencies-update.yml
  .github/workflows/release.yml
  pom.xml
Labels: dependencies

#721 ci: Qodana関連の設定修正
  .github/workflows/qodana-clone-finder.yml
  .github/workflows/qodana-quality.yml
  .gitignore
  .idea/misc.xml
  CONTRIBUTING.md
  qodana.yml
Labels: 🐛bug, documentation

#725 refactor: Qodanaの品質問題解決
  .github/qodana.sarif.json
  .github/workflows/qodana-quality.yml
  qodana.yml
  src/main/java/com/jaoafa/mymaid4/Main.java
  src/main/java/com/jaoafa/mymaid4/command/Cmd_Bug.java
  src/main/java/com/jaoafa/mymaid4/command/Cmd_Ded.java
  src/main/java/com/jaoafa/mymaid4/command/Cmd_Help.java
  src/main/java/com/jaoafa/mymaid4/command/Cmd_Home.java
  src/main/java/com/jaoafa/mymaid4/command/Cmd_Wire.java
  src/main/java/com/jaoafa/mymaid4/event/Event_AntiToolbar.java
  src/main/java/com/jaoafa/mymaid4/event/Event_Ded.java
  src/main/java/com/jaoafa/mymaid4/event/Event_History.java
  src/main/java/com/jaoafa/mymaid4/event/Event_NewPlayerAutoBlMap.java
  src/main/java/com/jaoafa/mymaid4/event/Event_ServerExceptionCatcher.java
  src/main/java/com/jaoafa/mymaid4/event/Event_ViaVerCheck.java
  src/main/java/com/jaoafa/mymaid4/event/Event_jaoBox.java
  src/main/java/com/jaoafa/mymaid4/httpServer/HTTP_VoteFill.java
  src/main/java/com/jaoafa/mymaid4/httpServer/MyMaidServer.java
  src/main/java/com/jaoafa/mymaid4/lib/Historyjao.java
  src/main/java/com/jaoafa/mymaid4/lib/MyMaidLibrary.java
  src/main/java/com/jaoafa/mymaid4/lib/TeleportAlias.java
  src/main/java/com/jaoafa/mymaid4/tasks/Task_CVE_2021_44228.java
Labels: ♻improvement

#735 fix: 南の楽園の場所を変更
  pom.xml
  src/main/java/com/jaoafa/mymaid4/event/Event_EBan.java
  src/main/java/com/jaoafa/mymaid4/event/Event_Jail.java
  src/main/java/com/jaoafa/mymaid4/lib/EBan.java
  src/main/java/com/jaoafa/mymaid4/lib/Jail.java
  src/main/java/com/jaoafa/mymaid4/lib/MyMaidData.java
  src/main/java/com/jaoafa/mymaid4/lib/MyMaidLibrary.java
Labels: ♻improvement

#743 fix: jSA2が正常に動作しなくなる不具合修正
  pom.xml
Labels: 🐛bug

#746 fix: jail時の警告処理でnullpointerが発生する不具合の修正
  src/main/java/com/jaoafa/mymaid4/event/Event_Jail.java
Labels: 🐛bug

#757 fix: #754 四角色の計算式修正（+テストケース追加）
  src/main/java/com/jaoafa/mymaid4/lib/SKKColorManager.java
  src/test/java/com/jaoafa/mymaid4/SKKColorTest.java
Labels: 🐛bug

#758 fix: #756 dt tpコマンドにて、第4引数のMarkerNameのところでMarkerTypeのサジェストが出てくる問題を修正
  src/main/java/com/jaoafa/mymaid4/command/Cmd_DT.java
Labels: 🐛bug

#770 依存パッケージアップデート 2022/03/28
  .github/workflows/PaperServerTest.yml
  .github/workflows/build.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/dependencies-update.yml
  .github/workflows/qodana-quality.yml
  .github/workflows/release.yml
  pom.xml
Labels: dependencies
